# Generated by Django 3.0.8 on 2020-07-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20200716_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='customerId',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
