# Generated by Django 3.0.8 on 2020-07-17 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_user_customerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='deliveryAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='isPrimary',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='package',
            name='package_user',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='package',
            name='postalCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='unitNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
