# Generated by Django 3.0.8 on 2020-07-17 12:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_auto_20200717_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddressentity',
            name='deliveryAddressId',
        ),
        migrations.AddField(
            model_name='deliveryaddressentity',
            name='deliveryAddress',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliveryaddressentity',
            name='packageID',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='backoffice.Package'),
        ),
    ]
