# Generated by Django 3.0.8 on 2020-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_auto_20200717_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
