# Generated by Django 3.0.8 on 2020-07-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0006_auto_20200717_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='pickupAddress',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
