# Generated by Django 3.0.8 on 2020-07-21 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_package_pickupaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reg_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ride_category', models.CharField(blank=True, choices=[('SUV', 'SUV'), ('PICKUP TRUCK', 'PICKUP TRUCK'), ('T_35_TRUCK', 'T_35_TRUCK'), ('T_50_TRUCK', 'T_50_TRUCK'), ('STATION WAGON', 'STATION WAGON'), ('HATCHBACK', 'HATCHBACK'), ('MINIVAN', 'MINIVAN'), ('Refrigerator Truck', 'Refrigerator Truck'), ('SEDAN', 'SEDAN')], default='SUV', max_length=100, null=True)),
                ('owner', models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
