# Generated by Django 3.0.8 on 2020-07-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_rides_maxweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rides',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
