# Generated by Django 3.0.8 on 2020-07-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_auto_20200727_2347'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestaurantEntity',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='customisableItemEntities',
            new_name='currentState',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='customisableItemId',
            new_name='deliveryAddressCity',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='deliveryAddress',
            new_name='deliveryAddressNeigbhourhood',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='foodItemEntities',
            new_name='deliveryAddressResidence',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='menuItemEntity',
            new_name='pickupAddressCity',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='pickupAddress',
            new_name='pickupAddressNeigbhourhood',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='postalCode',
            new_name='pickupAddressResidence',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='street',
            new_name='quanity',
        ),
        migrations.RenameField(
            model_name='package',
            old_name='unitNumber',
            new_name='weight',
        ),
        migrations.RemoveField(
            model_name='package',
            name='valid',
        ),
        migrations.AddField(
            model_name='package',
            name='measure',
            field=models.CharField(blank=True, choices=[('meters', 'meters'), ('kg', 'kg'), ('ltrs', 'ltrs')], default='kg', max_length=100, null=True),
        ),
    ]
