# Generated by Django 3.0.8 on 2020-07-31 07:03

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0012_auto_20200731_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='location',
            new_name='deliveryLocation',
        ),
        migrations.AddField(
            model_name='package',
            name='pickupLocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
