# Generated by Django 3.0.8 on 2020-08-08 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_auto_20200731_0708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='pickupLocation',
            new_name='location',
        ),
    ]
