# Generated by Django 3.0.8 on 2020-08-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0015_auto_20200808_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageBids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageOwner', models.CharField(blank=True, max_length=100, null=True)),
                ('packageID', models.CharField(blank=True, max_length=100, null=True)),
                ('bidderEmail', models.CharField(blank=True, max_length=100, null=True)),
                ('bidPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('bidderPickupTime', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
