# Generated by Django 3.0.8 on 2020-08-10 22:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0016_packagebids'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedBids',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bidID', models.CharField(blank=True, max_length=100, null=True)),
                ('timeAccepted', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='packagebids',
            name='id',
        ),
        migrations.AddField(
            model_name='package',
            name='courierState',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='packagebids',
            name='bidID',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='packagebids',
            name='bidState',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
