# Generated by Django 3.0.8 on 2020-08-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_auto_20200810_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acceptedbids',
            name='timeAccepted',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
