# Generated by Django 3.0.8 on 2020-08-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0020_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='car_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
