# Generated by Django 3.0.8 on 2020-08-17 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0021_auto_20200816_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('package_id', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='package',
            old_name='currentState',
            new_name='biddingState',
        ),
        migrations.AlterField(
            model_name='package',
            name='courierState',
            field=models.CharField(blank=True, choices=[('pickupPoint', 'pickupPoint'), ('intransit', 'intransit'), ('delivered', 'delivered'), ('returning', 'returning'), ('returned', 'returned')], default='pickupPoint', max_length=100, null=True),
        ),
    ]
