# Generated by Django 3.0.8 on 2020-08-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0022_auto_20200817_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='rides',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='rides',
            name='ride_category',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('PICKUP', 'PICKUP'), ('STATIONWAGON', 'STATION WAGON'), ('HATCHBACK', 'HATCHBACK'), ('MINIVAN', 'MINIVAN'), ('RefrigeratorTruck', 'RefrigeratorTruck'), ('SEDAN', 'SEDAN')], default='SUV', max_length=100, null=True),
        ),
    ]
