# Generated by Django 3.0.8 on 2020-08-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0023_auto_20200817_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='reg_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
