# Generated by Django 3.0.8 on 2020-08-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0024_file_reg_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='picture',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='file',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
