# Generated by Django 3.0.8 on 2020-08-20 03:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0025_auto_20200818_0539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(blank=True, max_length=100, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('years_experience', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('license_class', models.CharField(blank=True, choices=[('One', 'One'), ('Two', 'Two'), ('Four', 'Four'), ('Five', 'Five')], default='Four', max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='measure',
            field=models.CharField(blank=True, choices=[('Meters', 'Meters'), ('Kilograms', 'Kilograms'), ('Liters', 'Liters'), ('Mililitres', 'Mililitres')], default='Kilograms', max_length=100, null=True),
        ),
    ]
