# Generated by Django 3.0.8 on 2020-08-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0026_auto_20200820_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('version_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('app_version', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('app_upload_date', models.TimeField(auto_now_add=True, null=True)),
                ('app_expire_date', models.TimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'Apps Management',
                'verbose_name_plural': 'Apps Management',
            },
        ),
    ]
