# Generated by Django 3.0.8 on 2020-08-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0028_auto_20200820_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='country',
            field=models.CharField(blank=True, choices=[('Zimbabwe', 'Zimbabwe'), ('Zambia', 'Zambia')], default='Zimbabwe', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='deliveryAddressCity',
            field=models.CharField(blank=True, choices=[('Gweru', 'Gweru'), ('Harare', 'Harare'), ('Mutare', 'Mutare'), ('Bulawayo', 'Bulawayo'), ('Victoria Falls', 'Victoria_Falls'), ('Beitbridge', 'Beitbridge')], default='Harare', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='pickupAddressCity',
            field=models.CharField(blank=True, choices=[('Gweru', 'Gweru'), ('Harare', 'Harare'), ('Mutare', 'Mutare'), ('Bulawayo', 'Bulawayo'), ('Victoria Falls', 'Victoria_Falls'), ('Beitbridge', 'Beitbridge')], default='Gweru', max_length=100, null=True),
        ),
    ]
