# Generated by Django 3.0.8 on 2020-08-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0029_auto_20200821_0440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='file',
        ),
        migrations.AddField(
            model_name='driver',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
