# Generated by Django 3.0.8 on 2020-08-23 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0030_auto_20200823_0629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='file',
            new_name='picture',
        ),
    ]
