# Generated by Django 3.0.8 on 2020-08-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0031_auto_20200823_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='picture',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='picture',
        ),
        migrations.AddField(
            model_name='driver',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
