# Generated by Django 3.0.2 on 2020-05-06 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.TextField(blank=True, null=True)),
                ('old_price', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/vendor_images')),
                ('time', models.DateTimeField()),
                ('time_update', models.DateTimeField()),
                ('visibility', models.IntegerField(blank=True, null=True)),
                ('shop_categorie', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('order_limits', models.IntegerField(blank=True, null=True)),
                ('unit_measurement', models.TextField(blank=True, null=True)),
                ('procurement', models.IntegerField(blank=True, null=True)),
                ('in_slider', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('virtual_products', models.IntegerField(blank=True, null=True)),
                ('brand_id', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('vendor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
