# Generated by Django 3.0.8 on 2020-08-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200812_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='targetMarket',
        ),
        migrations.AddField(
            model_name='brand',
            name='targetMarket',
            field=models.ManyToManyField(to='products.TargetMarket'),
        ),
    ]
